Repository FRONTENDSCHOOL10/ssagwa-kurly, pull requests merged in 2024-07, with the labels that each got.

#15 Refactor: HTML 구조 정리 및 CSS 임포트 방식 변경
  src/index.html
Labels: 🔨 Refactor

#20 Docs: .gitignore 파일 수정
  .gitignore
Labels: 📃 Docs, ⚙ Setting

#22 Refactor: global.css - 공통된 스타일 작성
  src/index.html
  src/styles/global.css
Labels: 🎨 Style

#23 Feat: 헤더 마크업 및 스타일링 일부 구현
  src/assets/logo.svg
  src/assets/svg/Group.svg
  src/assets/svg/Hamburger.svg
  src/assets/svg/Icon_down.png
  src/assets/svg/MenuIcon-Baby.svg
  src/assets/svg/MenuIcon-Bread.svg
  src/assets/svg/MenuIcon-Coffee.svg
  src/assets/svg/MenuIcon-Cook.svg
  src/assets/svg/MenuIcon-Cosmetics.svg
  src/assets/svg/MenuIcon-Detergent.svg
  src/assets/svg/MenuIcon-Dog.svg
  src/assets/svg/MenuIcon-Food.svg
  src/assets/svg/MenuIcon-Fruit.svg
  src/assets/svg/MenuIcon-Gift.svg
  src/assets/svg/MenuIcon-Health.svg
  src/assets/svg/MenuIcon-HomeAppliances.svg
  src/assets/svg/MenuIcon-Meat.svg
  src/assets/svg/MenuIcon-Oil.svg
  src/assets/svg/MenuIcon-Salad.svg
  src/assets/svg/MenuIcon-SeaFood.svg
  src/assets/svg/MenuIcon-Snack.svg
  src/assets/svg/MenuIcon-TraditionalLiquor.svg
  src/assets/svg/MenuIcon-Travel.svg
  src/assets/svg/MenuIcon-Vegetable.svg
  src/assets/svg/MenuIcon-Wine.svg
  src/assets/svg/MenuIcon-shampoo.svg
  src/assets/svg/Search.svg
  src/components/header/header.css
  src/components/header/header.js
  src/components/header/index.html
Labels: ✨ Feat

#16 Feat: 푸터 웹 컴포넌트
  src/assets/svg/isms.svg
  src/assets/svg/logo_privacy.svg
  src/assets/svg/logo_tosspayments.svg
  src/assets/svg/logo_wooriBank.svg
  src/components/footer/footer.css
  src/components/footer/footer.js
  src/components/footer/index.html
Labels: ✨ Feat, 🎨 Style

#35 Feat: 헤더 카테고리 메뉴 아이템 컴포넌트 구현 및 적용
  src/components/header-category/headerCategory.js
  src/components/header/header.css
  src/components/header/header.js
  src/components/header/index.html
Labels: ✨ Feat, 🔨 Refactor

#39 Feat: sr-only 클래스
  src/styles/global.css
  src/styles/sr-only.css
Labels: ✨ Feat, 🎨 Style

#43 Design: 메인 페이지 Header/Footer 컴포넌트 적용
  index.html
  public/nosorry.png
  src/styles/style.css
Labels: 🎨 Style

#44 BugFix: Css preview에서 적용불가한거 해결 import방식 변경
  index.html
  main.js
  package.json
  src/components/footer/footer.js
  src/components/header/header.js
Labels: 🐞 BugFix, ⚙ Setting

#33 Refactor: 스크롤 이벤트 보완 및 헤더 마크업/스타일링 리팩토링
  src/components/header/header.css
  src/components/header/header.js
  src/components/header/index.html
Labels: 🥰 Accessibility, 🔨 Refactor, 🎨 Style

#46 Bulid: pocketbase패키지설치및 함수추가
  package-lock.json
  package.json
  src/api/pocketbase.js
  src/lib/utils/tiger.js
Labels: 📬 API, ✨ Feat

#24 Feat: Stepper 컴포넌트
  src/assets/svg/Minus.svg
  src/assets/svg/Plus.svg
  src/components/stepper/index.html
  src/components/stepper/stepper.css
  src/components/stepper/stepper.js
Labels: 🧶 Components, ✨ Feat, 🎨 Style

#17 Feat: 버튼 컴포넌트 구현
  src/components/button/button.css
  src/components/button/index.html
Labels: 🧶 Components, ✨ Feat, 🎨 Style

#48 Feat: pocket호스트 주소받아오기위한 .env파일생성
  .env
Labels: ⚙ Setting

#53 Refactor: 푸터 svg아이콘 성능향상을위한 경로수정
  src/components/footer/footer.js
Labels: 🔨 Refactor

#56 Refactor: stepper 컴포넌트 svg 경로 수정
  src/components/stepper/stepper.css
Labels: 🔨 Refactor

#57 Revert Feat: productlist paginator
  src/assets/svg/Previouspage.svg
  src/assets/svg/firstpage.svg
  src/assets/svg/lastpage.svg
  src/assets/svg/nextpage.svg
  src/components/paginator/index.html
  src/components/paginator/paginator.css
Labels: 🐞 BugFix

#50 Feat: 공통 컴포넌트 - Input 제작
  src/components/input/index.html
  src/components/input/input.css
Labels: 🧶 Components, ✨ Feat, 🎨 Style

#34 Feat: 장바구니 모달 컴포넌트 마크업/스타일링 구현
  public/svg/Badge-Fill.svg
  public/svg/Badge-Reward.svg
  public/svg/Badge-Stoke.svg
  public/svg/Badge-notice.svg
  src/components/cartModal/cartModal.css
  src/components/cartModal/cartModal.js
  src/components/cartModal/data.js
  src/components/cartModal/index.html
  src/components/footer/index.html
  src/lib/index.js
  src/lib/math/comma.js
  src/lib/math/index.js
Labels: 🧶 Components, ✨ Feat

#61 Feat: 공통함수 추가
  src/lib/dom/attr.js
  src/lib/dom/css.js
  src/lib/dom/getNode.js
  src/lib/dom/index.js
  src/lib/dom/insert.js
  src/lib/error/index.js
  src/lib/error/refError.js
  src/lib/error/syntaxError.js
  src/lib/error/typeError.js
  src/lib/index.js
  src/lib/math/calcDiscountPrice.js
  src/lib/math/index.js
  src/lib/utils/getPbImageURL.js
  src/lib/utils/index.js
  src/lib/utils/setDocumentTitle.js
  src/lib/utils/storage.js
  src/lib/utils/typeOf.js
Labels: ⚙ Setting, ✨ Feat

#63 Design: 헤더 z-index 값 수정
  src/components/header/header.css
Labels: 🔨 Refactor, 🎨 Style

#66 Design: 헤더 로고 이미지 변경
  public/logo.svg
Labels: 🎨 Style

#68 Modify: 헤더 position 속성 변경 및 고객센터 메뉴 z-index 조정
  src/components/header/header.css
Labels: 🔨 Refactor

#25 Feat: productlist 카테고리 구현 [일부미완]
  src/components/product_filter/filter.css
  src/components/product_filter/filter.js
  src/components/product_filter/index.html
Labels: 🧶 Components, 🥰 Accessibility, ✨ Feat, 🎨 Style

#74 Refactor: stepper 컴포넌트 모듈화
  src/components/stepper/index.html
  src/components/stepper/stepper.js
  src/components/stepper/stepper_modul.js
Labels: 🧶 Components, 🔨 Refactor

#72 Refactor: component input 수정
  src/components/button/button.css
  src/components/input/index.html
  src/components/input/input.css
Labels: 🧶 Components, 🔨 Refactor

#69 Feat: 장바구니 페이지 마크업 / 스타일링 구현
  src/pages/cart/cart.css
  src/pages/cart/cart.js
  src/pages/cart/index.html
Labels: ✨ Feat

#70 Feat: 장바구니 아코디언 컴포넌트 마크업/스타일링 및 일부 기능 구현
  public/svg/Arrow-Down.svg
  public/svg/Arrow-Left.svg
  public/svg/Arrow-Right.svg
  public/svg/Arrow-Up.svg
  public/svg/Check-Checked.svg
  public/svg/Check-UnChecked.svg
  public/svg/Food-Frozen.svg
  public/svg/Food-Normal.svg
  public/svg/Food-Refrigerated.svg
  src/components/cart-accordion/cartAccordion.css
  src/components/cart-accordion/cartAccordion.js
  src/components/cart-accordion/index.html
Labels: ✨ Feat

#27 [Feat] 공통 컴포넌트 - product(sale포함) 컴포넌트
  src/components/product/index.html
  src/components/product/product.css
  src/components/product/product.js
Labels: 🧶 Components, 🥰 Accessibility, ✨ Feat, 🎨 Style

#76 Feat: 회원가입 페이지 마크업 및 스타일링
  public/svg/Check.svg
  public/svg/Radio.svg
  src/pages/register/index.html
  src/pages/register/register.css
  src/pages/register/register.js
  vite.config.js
Labels: ✨ Feat, 🎨 Style

#80 Refator: 상품공통컴포넌트 리팩토링
  src/components/product/product.css
  src/components/product/product.js
Labels: 🧶 Components, 💬 Code Review, 🔨 Refactor

#82 Feat: VITE_PB_API 추가 및 getPbImageURL 함수 기본값수정
  .env
  src/lib/utils/getPbImageURL.js
Labels: 🐞 BugFix, 📬 API, ✨ Feat

#64 Feat: 상품 리스트 페이지
  src/components/footer/footer.css
  src/components/pagenatior/index.html
  src/components/pagenatior/pagenatior.css
  src/components/product/product.js
  src/components/product_filter/filter.js
  src/lib/dom/attr.js
  src/pages/productlist/index.html
  src/pages/productlist/productlist.css
  src/pages/productlist/productlist.js
  vite.config.js
Labels: ✨ Feat, 🎨 Style

#84 Feat: 회원가입 페이지 기능 구현 (일부)
  src/pages/register/index.html
  src/pages/register/register.css
  src/pages/register/register.js
Labels: ✨ Feat

#32 [Feat] 로그인 페이지 구현
  src/pages/login/index.html
  src/pages/login/login.css
  src/pages/login/login.js
  vite.config.js
Labels: 🥰 Accessibility, ✨ Feat, 🎨 Style

#30 feat: main페이지
  index.html
  main.js
  public/svg/arrow2.svg
  src/assets/images/banner/line-banner 1.png
  src/components/header/header.css
  src/pages/main/index.html
  src/pages/main/main.css
  src/pages/main/main.js
  src/pages/main/swiper.js
  src/styles/style.css
Labels: 🥰 Accessibility, ✨ Feat, 🎨 Style

#87 Chore: 장바구니 페이지 관련 vite.config 설정 추가
  vite.config.js
Labels: 🌏 Deploy

#85 Feat: 장바구니 페이지 기능 일부 구현 및 CSS 수정
  src/components/cart-accordion/cartAccordion.css
  src/components/cart-accordion/cartAccordion.js
  src/components/header/header.css
  src/pages/cart/cart.css
  src/pages/cart/cart.js
  src/pages/cart/index.html
Labels: ✨ Feat, 🎨 Style

#92 [BugFix]page-login 로그인 인풋 수정
  src/pages/login/index.html
Labels: 🎨 Style

#93 Modify: 라이브러리 함수적용
  src/components/product_filter/filter.js
Labels: ✨ Feat

#94 Modify: 헤더 페이지 라우팅 설정 및 헤더 z-index 수정
  src/components/header/header.css
  src/components/header/header.js
Labels: 📃 Docs, 🎨 Style

#96 Refactor: 장바구니 - 비로그인 상태일 때 화면 CSS 수정
  src/pages/cart/cart.js
Labels: 🔨 Refactor, 🎨 Style

#97 Modify: 헤더 페이지 라우팅 설정
  src/components/header/header.js
Labels: 🔨 Refactor

#102 Feat: Modal 창 제작
  src/components/modal/index.html
  src/components/modal/modal.css
  src/components/modal/modal.js
Labels: 🧶 Components, 🎨 Style

#112 [BugFix] 메인페이지-상품 0% 수정
  src/pages/main/main.js
Labels: 🐞 BugFix

#104 Refactor: login 페이지 코드 보수
  src/pages/login/index.html
  src/pages/login/login.css
  src/pages/login/login.js
Labels: 🔨 Refactor

#106 Refacrot: 모달창 코드 보수
  src/components/modal/modal.css
  src/components/modal/modal.js
Labels: 🔨 Refactor

#107 Feat: 회원가입 시 조건 추가
  src/pages/register/index.html
  src/pages/register/register.css
  src/pages/register/register.js
Labels: ✨ Feat

#116 Feat: 상품 상세페이지 구현
  .env
  public/svg/Bell.svg
  public/svg/Squre.svg
  public/svg/checklist.svg
  public/svg/cool_price.svg
  public/svg/delivery.svg
  public/svg/kurlyonly.svg
  public/svg/recycle.svg
  src/lib/utils/getPbImageURL.js
  src/pages/product/index.html
  src/pages/product/product.css
  src/pages/product/product.js
  vite.config.js
Labels: 📬 API, ✨ Feat, 🎨 Style

#118 Modify: 상세페이지 연결
  src/pages/main/main.js
  src/pages/productlist/productlist.js
Labels: 🔨 Refactor

#119 Feat: 로컬스토리지 연결 및 미구현 기능 구현완료
  src/components/cart-accordion/accordionItem.js
  src/components/cart-accordion/cartAccordion.css
  src/components/cart-accordion/cartAccordion.js
  src/components/cart-accordion/index.html
  src/pages/cart/cart.css
  src/pages/cart/cart.js
  src/pages/cart/index.html
Labels: ✨ Feat, 🔨 Refactor, 🎨 Style

#120 Feat: 장바구니 모달 창 기능 추가 및 장바구니 담기 구현
  src/components/cartModal/cartModal.css
  src/components/cartModal/cartModal.js
  src/components/cartModal/data.js
  src/components/cartModal/index.html
Labels: ✨ Feat, 🎨 Style

#111 Feat: 상품리스트 필터기능 구현
  src/components/product_filter/filter.js
  src/pages/productlist/index.html
  src/pages/productlist/productlist.js
Labels: 📬 API, ✨ Feat

#115 Feat: 팝업 모달창
  src/components/popup/index.html
  src/components/popup/popup.css
  src/components/popup/popup.js
Labels: 🧶 Components, 🥰 Accessibility, ✨ Feat, 🎨 Style

#113 Feat: 공통 컴포넌트 - 최근 본 상품
  src/components/recent-product/index.html
  src/components/recent-product/recent.css
  src/components/recent-product/recent.js
Labels: 📬 API, 🧶 Components, ✨ Feat

#123 Feat: 모달창 버튼 2개 기능 추가
  src/components/modal/modal.css
  src/components/modal/modal.js
Labels: 🧶 Components, ✨ Feat

#125 Modify: viewModal 함수 매개변수 수정
  src/pages/login/login.js
  src/pages/product/product.js
  src/pages/register/register.js
Labels: 🧶 Components

#128 Feat: main popup 기능 구현
  src/components/popup/index.html
  src/components/popup/popup.css
  src/components/popup/popup.js
  src/pages/main/main.js
Labels: ✨ Feat

#134 Feat: 장바구니 상품 개별/선택 삭제 시 확인용 모달 적용
  public/svg/Check-Checked.svg
  src/components/cart-accordion/cartAccordion.css
  src/components/cart-accordion/cartAccordion.js
Labels: ✨ Feat

#131 Feat: 장바구니 툴팁(버블 알림) 구현 완료
  src/components/cart-modal/cartModal.css
  src/components/cart-modal/cartModal.js
  src/components/tooltip/tooltip.css
  src/components/tooltip/tooltip.js
  src/pages/productlist/productlist.js
Labels: ✨ Feat

#126 Refactor:메인, 로그인페이지 html,css 문법 검사 수정
  index.html
  src/assets/images/banner/line-banner-1.png
  src/pages/login/index.html
  src/pages/login/login.css
  src/pages/main/index.html
  src/pages/main/main.css
Labels: 🔨 Refactor

#133 Feat: 후기 작성, 상품문의하기 구현
  src/components/popupProduct/index.html
  src/components/popupProduct/popupProduct.css
  src/components/popupProduct/popupProduct.js
Labels: ✨ Feat, 🎨 Style

#139 Feat: 장바구니 관련 유틸리티 함수 구현
  src/lib/utils/cartUtils.js
Labels: ✨ Feat

#135 Feat: 최근 본 상품 기능 구현
  src/components/recent-product/index.html
  src/components/recent-product/recent-product.css
  src/components/recent-product/recent-product.js
  src/components/recent-product/recent.css
  src/components/recent-product/recent.js
  src/pages/main/main.js
  src/pages/product/product.js
  src/pages/productlist/productlist.js
Labels: ✨ Feat

#136 Bugfix: main popup 이미지 경로 수정
  index.html
  src/assets/images/banner/line-banner.png
  src/assets/images/popup/ea7e5e29-f8e5-4f65-934a-62432df4b337.png
  src/components/popup/popup.js
Labels: 🐞 BugFix

#141 Feat: 상세 페이지 장바구니 담기 버튼 기능 추가
  src/assets/images/banner/line-banner-1.png
  src/components/recent-product/recent-product.css
  src/components/tooltip/tooltip.css
  src/lib/utils/index.js
  src/pages/main/index.html
  src/pages/product/product.js
Labels: ✨ Feat

#142 Refactor: 헤더 로그인 여부 별 화면 구성 / 로그아웃 기능 추가 등
  src/components/header/header.css
  src/components/header/header.js
Labels: 🔨 Refactor, 🎨 Style

#144 Refactor: 웹 표준 검사 완료
  src/components/cart-accordion/cartAccordion.js
  src/pages/cart/cart.css
  src/pages/cart/index.html
Labels: 🔨 Refactor

#145 Feat: 장바구니 상품 클릭 시 상품 상세페이지로 링크 연결
  src/components/cart-accordion/accordionItem.js
  src/components/cart-accordion/cartAccordion.css
Labels: ✨ Feat, 🔨 Refactor

#148 Refator: 크기수정
  src/components/footer/footer.css
  src/components/product/product.css
Labels: 🔨 Refactor

#147 Refactor: 장바구니 유틸리티 함수 async/await 적용
  src/lib/utils/cartUtils.js
Labels: 🔨 Refactor

#152 Feat: 메인페이지 상품, 스크롤 키보드Feat/main add to cart
  index.html
  src/assets/images/banner/banner01.webp
  src/assets/images/banner/banner02.webp
  src/assets/images/banner/banner03.webp
  src/assets/images/banner/banner05.webp
  src/assets/images/banner/line-banner-1.webp
  src/pages/main/main.js
  src/pages/main/swiper.js
Labels: 🐞 BugFix, ✨ Feat, 🔨 Refactor

#153 Modify: 메인 팝업 및 최근 본 상품 개수 수정
  src/assets/images/popup/popup1.png
  src/components/popup/popup.js
  src/components/recent-product/recent-product.js
Labels: 🐞 BugFix

#154 Feat: 페이지 넘겼을때 페이지 URL추가
  src/components/header/header.css
  src/pages/productlist/productlist.js
Labels: 📬 API, ✨ Feat

#158 Refactor: 장바구니 유틸 함수 수정
  src/lib/utils/cartUtils.js
Labels: 🔨 Refactor

#159 BugFix: 장바구니 페이지 금액 반영 관련 오류 수정
  src/components/cart-accordion/cartAccordion.js
  src/pages/cart/cart.css
  src/pages/cart/cart.js
  src/pages/cart/index.html
Labels: 🐞 BugFix

#163 Refactor: final modify
  index.html
  src/assets/images/banner/line-banner.webp
  src/components/cart-accordion/accordionItem.js
  src/components/cart-accordion/cartAccordion.js
  src/components/cart-modal/cartModal.js
  src/components/header/header.js
  src/components/modal/modal.js
  src/components/popup/popup.js
  src/components/popupProduct/index.html
  src/components/popupProduct/popupProduct.js
  src/components/product/product.js
  src/components/product_filter/filter.js
  src/components/tooltip/tooltip.js
  src/pages/cart/cart.js
  src/pages/cart/index.html
  src/pages/login/login.js
  src/pages/main/main.css
  src/pages/main/main.js
  src/pages/main/swiper.js
  src/pages/product/product.js
  src/pages/productlist/index.html
  src/pages/productlist/productlist.js
  src/pages/register/register.js
Labels: 🥰 Accessibility, 🔨 Refactor

#164 Bugfix: final modify
  index.html
  src/components/header/header.css
  src/components/header/header.js
  src/pages/main/main.css
Labels: 🐞 BugFix

#166 Feat: 오픈 그래프 프로토컬 추가
  index.html
  src/pages/login/index.html
  src/pages/productlist/index.html
  src/pages/register/index.html
Labels: ✨ Feat

#167 Refactor: 비밀번호 조건 변경
  src/pages/product/product.js
  src/pages/register/index.html
  src/pages/register/register.js
Labels: 🔨 Refactor

#168 Create: ReadMe.md 추가
  README.md
Labels: 📃 Docs

#170 Modify: 불필요한 주석 제거 및 헤딩 태그 수정
  src/components/cart-accordion/cartAccordion.js
Labels: 🔨 Refactor

#172 Feat: 회원 탈퇴 기능 구현
  src/components/header/header.css
  src/components/header/header.js
  src/components/modal/modal.js
  src/lib/utils/userWithdrawal.js
Labels: ✨ Feat

#174 bugfix: 이미지 크기 조절
  src/pages/product/product.css
Labels: 🐞 BugFix
